### ISSUE TITLE
How to compile and install this package?

### ISSUE THREAD

**Issue by lastproxy** [UVVIS-BIRA-IASB/qdoas#4]
The release source package doesn't have either `Makefile` or `config.pri`. It seems that I can not compile and install the source package in the Linux system [**following the S/W manual.**](https://uv-vis.aeronomie.be/software/QDOAS/QDOAS_manual.pdf) 
```
$ make distclean
$ qmake all.pro
$ make
``` 
It would be helpful if the Linux binary executable package could be available. By the way, `conda install` also did not work due to the incompatible system environment (low glibc version).

**Comment by tdanckaert** [comment]
Hi, the user manual is not up to date unfortunately.  Qdoas is now built using CMake.  In order to compile Qdoas yourself:

1. install CMake and development versions of all required libraries, such as HDF4, HDF5, NetCDF, Boost, Eigen, ... (see https://github.com/UVVIS-BIRA-IASB/qdoas?tab=readme-ov-file#compilation )
2. from the source root directory, run 
`mkdir build`
`cd build`
`cmake <CMAKE_OPTIONS> ..`
`make`

For the `cmake` step, `CMAKE_OPTIONS` should probably include options to inform cmake of the location of some required libraries such as `-DEigen3_DIR=<path/to/your/eigen3/installation`, and similar for boost, NetCDF, HDF, etc (depending on your system, some of these may be detected automatically).

We only provide linux binaries through conda.  Which linux distribution and version are you using?  I'm afraid we can't do much about the glibc version problem, as we rely on the conda-forge standard toolchains.

**Comment by lastproxy** [comment]
Thanks for your kind reply. I am using CentOS 6.10. I will try to install it from the source with `cmake` tool.
