### ISSUE TITLE
Program closes abruptly when Analysis output is enabled.

### ISSUE THREAD

**Issue by xnick-uy** [UVVIS-BIRA-IASB/qdoas#6]
Greetings.
I have a project that allows me to run analysis normally on my files, but whenever I try to set up the results to a text file, the program crashes abruptly after processing the first spectrum. The output file is created with the proper headers, and the results of a single analysis below. When output to a file is disabled, the analysis proceeds normally.

What am I doing wrong?
The format of my spectra is the old MFC from Heidelberg, and I'm running QDOAS version 3.5 and I recently upgraded to 3.6.8 to see if it solved the problem. The behaviour is the same, on different PCs running windows 10. Does it matter if my files are not named sequentially? (I had to screen out bad reading files).

If you have any ideas, I'll be happy to try. Thanks!

**Comment by tdanckaert** [comment]
Hi,
this sounds like a bug of some sorts.  It is probably the easiest if you can provide us with a full example (configuration, input file, reference spectra, cross sections, etc) so we can reproduce the problem here and look for the cause.  If you prefer not to share anything publicly, you can message me (thomasd) at the "official" QDOAS support forum https://forum.atmospherictoolbox.org/c/qdoas/ .

**Comment by xnick-uy** [comment]
[meas_mpi.zip](https://github.com/user-attachments/files/16948856/meas_mpi.zip)
[meas_uv.zip](https://github.com/user-attachments/files/16948857/meas_uv.zip)
[NO2_qdoas_project.zip](https://github.com/user-attachments/files/16948858/NO2_qdoas_project.zip)

Hi. Thanks for your reply. I registered to the atmospherictoolbox.org (user xnick) but I could not find a way to send a direct message or create a new topic with attached files. I'm putting my files over here on github (not meant to be shared but I don't think that's an issue).
- NO2_qdoas_project.zip: the xml qdoas file, alongside some other input files. 
- meas_uv.zip and meas_mpi.zip: spectra files in MFC format.

The xml file includes two projects, each one with three analysis windows focused on NO2 in different ranges (but my problem persist even when analyzing a single project with a single analysis window).

I've put the cross section files I'm using on a shared folder: https://drive.google.com/drive/folders/1swjodSCcj4nsr6IlpxW5GXQ8SGrol45u?usp=sharing

I'm a bit concerned about the qdoas project storing the absolute paths of the files. When sharing projects, or when working on different stations, extra steps are required to reconfigure all the paths. For the files I provided, I tried to place the bulk of the input files on an external drive (X: under windows).

**Comment by tdanckaert** [comment]
Hi, thanks for the files.  I think one file is still missing: the high resolution solar spectrum Solar_Fl_Vac_05.ktz.  ~~Could you send that one, too?  In the mean time I will try if I can make it work with one of our hi res spectra.~~

I got it to work and found the bug :)  There's a memory bug in QDOAS when selecting "Filename" for output.  I'll now prepare a new release of QDOAS, that will probably be available on conda-forge by tomorrow.  Until then, you can remove "File name" from the selected outut fields to make it work in the current version of QDOAS (though not having the file name might make it difficult to attribute the results to the correct spectrum later on?).

**Comment by xnick-uy** [comment]
Thank you very much. I'll try that right away, and update qdoas when available. I appreciate your efforts.

**Comment by bira-iasb-fayt** [comment]
Hello
Just a comment about MFC format (binary or std) produced by DOASIS and MS-DOAS
Because spectra are saved in individual files, the "Filename" field has been introduced in output in order to facilitate the search of a specific record.  In practice this format is not very comfortable for MAXDOAS analysis mainly for the selection of the reference spectrum of the day or the scans.  That's why we recommend to convert your spectra in the alternative MFC BIRA-IASB binary format with our tool MFC4QDOAS_Converter before processing in QDOAS.  This converter splits your collection of spectra files in daily files.   I send you a mail wit the information about this converter.
All the best

**Comment by tdanckaert** [comment]
Hi, qdoas 3.6.10 is now available from conda-forge.  Please let me know if it works as expected!

**Comment by xnick-uy** [comment]
Hello, Thomas.I've tested the new version and it is working as expected.
Thanks for all the work.
My goal now is to follow Caroline Fayt's suggestion and convert the old MFC
files to newer formats (MCF Bira to begin with, hopefully netcdf in the
future).

Best regards,
NC
